config/routes.rb
Knackle::Application.routes.draw do
  resources :messages


  resources :tasks


  resources :assignments


  resources :groups


  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => "home#index"

  match "groups/join/:id", to: "groups#join", as: "join_groups"
  match "groups/leave/:id", to: "groups#leave", as: "leave_groups"
  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :content, :deadline, :user_id, :group_id, :finished

  attr_accessible :photo
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  belongs_to :group
  belongs_to :user

  after_save :add_assignment
  after_save :update_group

  private

  def add_assignment
    if finished
      group = Group.find(group_id)
      members = group.users

      Rails.logger.info(members)

      assignee = members.order("RANDOM()").first

      task = Task.order("RANDOM()").first
      content = task.content

      task.used = true
      task.save

      Assignment.create(content: content, deadline: 1.hours.from_now - 1.minute, user_id: assignee.id, group_id: group_id, finished: false)
    end
  end

  def update_group
    group = Group.find(group_id)
    group.last_update = DateTime.now
    group.save
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render json: @assignment, status: :created, location: @assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment.group, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :finished %><br />
    <%= f.radio_button :finished, "0" %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>

  <%= f.file_field :photo %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.content %></td>
    <td><%= assignment.user_id %></td>
    <td><%= assignment.deadline %></td>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
    <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<div data-role="page">

  <div data-role="panel" id="panel" data-position="right" data-theme="a" data-display="push"></div>

  <div data-role="header">
    <a href="/groups/<%= @assignment.group.id %>" data-iconpos="notext" data-role="button" data-icon="home" title="Home" class="ui-btn-left ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-notext ui-btn-up-a" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="a">
    <span class="ui-btn-inner">
    <span class="ui-btn-text">Home</span>
    <span class="ui-icon ui-icon-back ui-icon-shadow">&nbsp;</span></span> </a>   
<h1><%= @assignment.user.name %></h1>
   
  </div>

  <div data-role="content" role="main">
   

    <ul class="listview" data-role="listview" data-inset="true">
      <li data-role="list-divider" data-theme="a">Assignment <%= @assignment.user.name %></li>
      <li>"<%= @assignment.content %>"</li>
      <li class="active"><data-icon="back">Succeeded <%= time_ago_in_words @assignment.updated_at %> ago, or not? You can decide.</li>
    </ul>
    
    
    <ul class="listview" data-role="listview" data-inset="true">
      <li data-role="list-divider" data-theme="a">Proof</li>
     <li> <center><%= image_tag @assignment.photo.url(:medium) %></center>
      </li>
    </ul>
    
</div>