config/routes.rb
Knackle::Application.routes.draw do
  resources :messages


  resources :tasks


  resources :assignments


  resources :groups


  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => "home#index"

  match "groups/join/:id", to: "groups#join", as: "join_groups"
  match "groups/leave/:id", to: "groups#leave", as: "leave_groups"
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :title, :last_update

  has_many :memberships, :dependent => :destroy  
  has_many :users, :through => :memberships

  has_many :assignments

  def add_assignment
   # if self.users.length >= 2
      Assignment.create(content: "Test", deadline: 12.hours.from_now, user_id: self.users.first.id, group: self.id, finished: false)
    #end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    #me = FbGraph::User.new('me', :access_token => session[:fb_access_token]).fetch
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    @active_assignment = Assignment.where(group_id: params[:id], finished: false)
    @active_user = @active_assignment.collect(&:user).first

    @messages = Message.where(group_id: params[:id]).order("updated_at DESC")[0..2]
    @message = Message.new

    @assignments = Assignment.where(group_id: @group.id).order("updated_at DESC")[0..3]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  def join
    group = Group.find(params[:id])
    if !current_user.groups.include? group
      current_user.groups << group
      current_user.save
    end

    redirect_to groups_url
  end

  def leave
    group = Group.find(params[:id])
    user_group = current_user.groups.find(group.id)
    
    if user_group
      current_user.groups.delete(user_group)
    end

    redirect_to groups_url
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
  <style type="text/css">
  
  .listview a { text-decoration:none; }
  .listview span { font-size:10px; }
  
  
  .active span { color:red; font-size:12px; }
  </style>

  <div data-role="page">

  <div data-role="panel" id="panel" data-position="right" data-theme="a" data-display="push"></div>

  <div data-role="header">
     <h1>Groups</h1>
  </div>

  <div data-role="content" role="main">
  
    <ul class="listview" data-role="listview" data-inset="true">
      <li data-role="list-divider" data-theme="a">Your groups (<%= current_user.groups.length %>)</li>
      <% current_user.groups.each do |group| %>
        <li>
          <% if group.assignments.where(finished: false).collect(&:user).first == current_user %>
            <a href="<%= url_for group %>" data-ajax="false" class="active">
              <%= group.title %> (<%= group.users.length %>)
              <span><br />
                <b>It's your turn, do your assignment!</b>
                <% if !group.last_update.nil? %>
                  Active <%= time_ago_in_words group.last_update %> ago
                <% end %>
              </span>
            </a>
          <% else %>
            <a href="<%= url_for group %>" data-ajax="false">
              <%= group.title %> (<%= group.users.length %>)
              <span><br />
                <% if !group.last_update.nil? %>
                  Active <%= time_ago_in_words group.last_update %> ago
                <% end %>
              </span>
            </a>
          <% end %>
        </li>
      <% end %>
    </ul>

    <ul class="listview" data-role="listview" data-inset="true">
      <li data-role="list-divider" data-theme="a">All groups</li>
      <% @groups.each do |group| %>
        <li><a href="/groups/join/<%= group.id %>"><%= group.title %> (<%= group.users.length %>)<span><Br><b></b></span></a></li>
      <% end %>
    </ul>

    <a href="/users/sign_out" data-method="delete" rel="nofollow" style="text-decoration: none;"><button data-theme="d" class="ui-btn-hidden" data-disabled="false">Sign out</button></a>
   
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
     <style type="text/css">
 div.fileinputs {
  position: relative;
}

div.fakefile {
  position: absolute;
  top: 0px;
  left: 0px;
  z-index: 1;
  width: 100%;
}

input.file {
  position: relative;
  text-align: right;
  -moz-opacity:0 ;
  filter:alpha(opacity: 0);
  opacity: 0;
  z-index: 2;
}

.ui-body-c.ui-input-text {
border:0px;
}
</style>
     
<div data-role="page">



  <div data-role="header">
<a href="/groups" data-iconpos="notext" data-role="button" data-icon="home" title="Home" class="ui-btn-left ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-notext ui-btn-up-a" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="a">
    <span class="ui-btn-inner">
    <span class="ui-btn-text">Home</span>
    <span class="ui-icon ui-icon-back ui-icon-shadow">&nbsp;</span></span>
    </a>     <h1><%= @group.title %></h1>
   
  </div>

  <div data-role="content" role="main">
  

    <ul class="listview" data-role="listview" data-inset="true">
      <% if @active_user == current_user %>
        <li data-role="list-divider" data-theme="a">Your assigment</li>
        <li>"<%= @active_assignment[0].content %>"</li>

        <%= form_for @active_assignment[0], html: {:'data-ajax' => "false"} do |f| %>
          <div class="fileinputs" >
            <%= f.file_field :photo, :accept => "image/*", :capture => "camera", class: "file" %>
            <div class="fakefile">
              <button data-theme="f" class="ui-btn-hidden" data-disabled="false">Select Picture</button>
            </div>
          </div>
            <div id="fb2" style="display:none;"><button data-theme="g" class="ui-btn-hidden" data-disabled="false">Loading Picture... <img style="height:20px;" src="/assets/ajax-loader.gif"></button></div>


          <%= f.hidden_field :finished, :value => true %>

          <div class="ui-block-b">
            <button data-icon="flat-cross" data-theme="d" class="ui-btn-hidden" data-disabled="false" onClick="alert('No option');">Failed</button>
          </div>
          
          <br /><br /><br />
        <% end %>

      <% elsif !@active_user.blank? %>
        <li data-role="list-divider" data-theme="a"><%= @active_user.name %> assigment</li>
        <li>"<%= @active_assignment[0].content %>"</li>
      <% end %>

    </ul>
    
     <!-- <button class="ui-btn-hidden" data-disabled="false">Upload Picture</button> -->
     
    <% if !@active_user.blank? %>
      <ul data-role="listview" data-inset="true">
        <li data-role="list-divider" data-theme="a"  data-disabled="false">Time-Left</li>
        <li id="tijd" class="time" style="padding:5px;"></li>
      </ul>
    <% end %>

    <ul class="listview" data-role="listview" data-inset="true">
      <li data-role="list-divider" data-theme="a">Chat</li>
      <% if !@messages.nil? %>
        <% @messages.each do |message| %>
          <li><%= message.content %><span><Br><%= message.user.name %> (<%= time_ago_in_words message.updated_at %> ago)</span></li>
        <% end %>
      <% end %>

      <%= form_for(@message) do |f| %>
          <%= f.text_field :content, placeholder: "Your message" %>

          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :group_id, value: @group.id %>

          <%= f.submit %>
      <% end %>
    </ul>
    
    <ul class="listview" data-role="listview" data-inset="true">
      <li data-role="list-divider" data-theme="a">Last 3 assignments</li>
      <% @assignments.each do |assignment| %>
        <% if assignment.finished %>
          <li><a href="<%= url_for assignment %>"><%= assignment.user.name %> (<%= time_ago_in_words assignment.updated_at %>)<span><Br><%= assignment.content %></span></a></li>
        <% end %>
      <% end %>
    </ul> 
  
    <ul class="listview" data-role="listview" data-inset="true">
      <li data-role="list-divider" data-theme="a">Members</li>
      <% @group.users.each do |user| %>
        <li><%= user.name %> <br><span>(<%= user.assignments.select{ |a| a.finished == true }.length %> completed)</span></li>
      <% end %>
    </ul> 

    <a href="/groups/leave/<%= @group.id %>" rel="nofollow" style="text-decoration: none;"><button data-theme="d" class="ui-btn-hidden" data-disabled="false">Leave group</button></a>
    
</div>

<script type="text/javascript">
<% if !@active_user.blank? %>
  function leftPad(number, targetLength) {
      var output = number + '';
      while (output.length < targetLength) {
          output = '0' + output;
      }
      return output;
  }

  function countDown(tijd)
  {
    var tijd = tijd - 1;
    var q = tijd / 3600;
    var qround = Math.floor(q);
    var tijd2 = tijd - qround * 3600;
    var x=tijd2%60;
    var z = tijd2/60;
    var y = Math.round(z);
    
    document.getElementById('tijd').innerHTML = leftPad(qround,2)+':'+leftPad(y,2)+':'+leftPad(x,2);
    setTimeout("countDown('"+tijd+"');", 1000);
  }
  countDown('<%= (@active_assignment[0].deadline - Time.now).round %>');
<% end %>



$('input[type=file]').change(function() { 
    // select the form and submit
    $('.fileinputs').css('display', 'none');
    $('#fb2').css('display', 'block');
    $('form').submit(); 
});     
     
</script>